// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	"github.com/petergtz/pegomock"
	webhooks "github.com/runatlantis/atlantis/server/events/webhooks"
	"reflect"
)

func AnyWebhooksApplyResult() webhooks.CommandResult {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*(webhooks.CommandResult))(nil)).Elem()))
	var nullValue webhooks.CommandResult
	return nullValue
}

func EqWebhooksApplyResult(value webhooks.CommandResult) webhooks.CommandResult {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue webhooks.CommandResult
	return nullValue
}
